// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh3PnY3kxgV_2SdduIBAJNN-aTjVFGSb4',
    appId: '1:699319563557:web:4789962a46df81a05896cc',
    messagingSenderId: '699319563557',
    projectId: 'note-app-dcef2',
    authDomain: 'note-app-dcef2.firebaseapp.com',
    storageBucket: 'note-app-dcef2.firebasestorage.app',
    measurementId: 'G-4NZH88FPG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1fWh9nBSMuUQ_l5UokG1rbeyokYKtBFg',
    appId: '1:699319563557:android:10f7f4bcd7ed74455896cc',
    messagingSenderId: '699319563557',
    projectId: 'note-app-dcef2',
    storageBucket: 'note-app-dcef2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeC0l2BnolngaRqbRiQCaPvyAIQWu_dAs',
    appId: '1:699319563557:ios:19a1ae7d04da57c55896cc',
    messagingSenderId: '699319563557',
    projectId: 'note-app-dcef2',
    storageBucket: 'note-app-dcef2.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeC0l2BnolngaRqbRiQCaPvyAIQWu_dAs',
    appId: '1:699319563557:ios:19a1ae7d04da57c55896cc',
    messagingSenderId: '699319563557',
    projectId: 'note-app-dcef2',
    storageBucket: 'note-app-dcef2.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh3PnY3kxgV_2SdduIBAJNN-aTjVFGSb4',
    appId: '1:699319563557:web:ca2a5df989f4a4045896cc',
    messagingSenderId: '699319563557',
    projectId: 'note-app-dcef2',
    authDomain: 'note-app-dcef2.firebaseapp.com',
    storageBucket: 'note-app-dcef2.firebasestorage.app',
    measurementId: 'G-VTEPGHH77T',
  );
}
